import {useEffect,useRef} from 'react';
import {Map as MapLibreMap,NavigationControl,setWorkerUrl} from 'maplibre-gl';
import workerUrl from '../node_modules/maplibre-gl/dist/maplibre-gl-worker.mjs?worker&url';
import 'maplibre-gl/dist/maplibre-gl.css';
import {SC} from './data.js';
setWorkerUrl(workerUrl);
const CENTER=[76.7794,30.7333];
const STYLES={Map:{version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,maxzoom:19}},layers:[{id:'osm',type:'raster',source:'osm'}]},Satellite:{version:8,sources:{sat:{type:'raster',tiles:['https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}'],tileSize:256,maxzoom:18}},layers:[{id:'sat',type:'raster',source:'sat'}]},Terrain:{version:8,sources:{osm:{type:'raster',tiles:['https://a.tile.opentopomap.org/{z}/{x}/{y}.png'],tileSize:256,maxzoom:17}},layers:[{id:'osm',type:'raster',source:'osm'}]}};
const on=v=>v!==0&&v!==false;
function coords(p){if(p.geometry?.coordinates?.[0]?.length)return p.geometry.coordinates[0];return (p.pts||'').split(' ').map(q=>q.split(',').map(Number));}
function toGeoJSON(parcels){return {type:'FeatureCollection',features:parcels.filter(p=>coords(p).length>=3).map(p=>{const ring=coords(p),closed=ring[0][0]===ring.at(-1)[0]&&ring[0][1]===ring.at(-1)[1];return {type:'Feature',properties:{id:p.id,ulpin:p.u,status:SC[p.s]||'#8A8A73',zone:p.z==='R'?'#8FB4E3':'#B7A3E0',trust:p.t},geometry:{type:'Polygon',coordinates:[closed?ring:[...ring,ring[0]]]}}})};}
function centroid(p){const a=coords(p);return a.reduce((s,q)=>[s[0]+q[0]/a.length,s[1]+q[1]/a.length],[0,0]);}
function flagGeoJSON(parcels){return {type:'FeatureCollection',features:parcels.flatMap(p=>{if(!p.flags)return[];const c=centroid(p);return [['encroachmentSuspected','enc','#DC2626'],['staleRecord','stale','#6B7280'],['dataMismatch','mis','#F59E0B']].filter(([key])=>p.flags[key]).map(([,,color])=>({type:'Feature',properties:{k:color},geometry:{type:'Point',coordinates:c}}))})};}
export default function Map3D({parcels=[],sel,mstyle,layers,onSelect,onMoveEnd,center=CENTER,flags=false,z0=15}){
 const box=useRef(),map=useRef(),cur=useRef({});cur.current={parcels,sel,layers,onSelect,onMoveEnd,center,flags,z0};
 const refresh=()=>{const m=map.current;if(!m?.getSource('parcels'))return;const c=cur.current;m.getSource('parcels').setData(toGeoJSON(c.parcels));m.getSource('flags')?.setData(flagGeoJSON(c.parcels));try{m.setPaintProperty('parcels-fill','fill-color',on(c.layers?.zones)?['get','zone']:'rgba(255,255,255,.3)');m.setPaintProperty('parcels-line','line-color',on(c.layers?.status)?['get','status']:'#888');m.setFilter('parcels-sel',['==',['get','id'],c.sel??'']);['#DC2626','#6B7280','#F59E0B'].forEach(k=>m.getLayer('flag-'+k)&&m.setLayoutProperty('flag-'+k,'visibility',c.flags&&on(c.layers?.[k])?'visible':'none'))}catch{}}
 const ensure=()=>{const m=map.current;if(!m||m.getSource('parcels'))return;const c=cur.current;m.addSource('parcels',{type:'geojson',data:toGeoJSON(c.parcels)});m.addLayer({id:'parcels-fill',type:'fill',source:'parcels',paint:{'fill-color':['get','zone'],'fill-opacity':.7}});m.addLayer({id:'parcels-case',type:'line',source:'parcels',paint:{'line-color':'#fff','line-width':6,'line-opacity':.9}});m.addLayer({id:'parcels-line',type:'line',source:'parcels',paint:{'line-color':['get','status'],'line-width':3}});m.addLayer({id:'parcels-sel',type:'line',source:'parcels',filter:['==',['get','id'],''],paint:{'line-color':'#1E72D1','line-width':5}});m.addSource('flags',{type:'geojson',data:flagGeoJSON(c.parcels)});['#DC2626','#6B7280','#F59E0B'].forEach(color=>m.addLayer({id:'flag-'+color,type:'circle',source:'flags',filter:['==',['get','k'],color],paint:{'circle-radius':7,'circle-color':color,'circle-stroke-color':'#fff','circle-stroke-width':2}}));refresh();};
 useEffect(()=>{const m=new MapLibreMap({container:box.current,style:STYLES[mstyle]||STYLES.Satellite,center,zoom:z0,pitch:35,bearing:-10});map.current=m;m.addControl(new NavigationControl(),'top-right');m.on('load',ensure);m.on('style.load',ensure);m.on('moveend',()=>{const b=m.getBounds();cur.current.onMoveEnd?.([b.getWest(),b.getSouth(),b.getEast(),b.getNorth()])});m.on('click','parcels-fill',e=>onSelect?.(e.features?.[0]?.properties?.id));m.on('mouseenter','parcels-fill',()=>m.getCanvas().style.cursor='pointer');m.on('mouseleave','parcels-fill',()=>m.getCanvas().style.cursor='');return()=>m.remove()},[]);
 useEffect(()=>{if(map.current)map.current.setStyle(STYLES[mstyle]||STYLES.Satellite)},[mstyle]);useEffect(refresh,[parcels,sel,layers,flags]);
 useEffect(()=>{const p=parcels.find(x=>x.id===sel),m=map.current;if(p&&m){const c=centroid(p);m.flyTo({center:c,zoom:Math.max(z0+1.5,16),duration:800})}},[sel]);
 useEffect(()=>{map.current?.flyTo({center,zoom:z0,duration:900})},[center,z0]);
 return <div ref={box} style={{position:'absolute',inset:0}}/>;
}
